### ISSUE TITLE
Improve Documentation and Clarify Bot Message Tags

### ISSUE THREAD

**Issue by memExpert** [vorchunpaul/zetmemo#3]
I believe the application would benefit from more detailed documentation, specifically regarding its purpose and intended use. A clearer explanation would help users better understand the value it offers.

Additionally, I am unclear about the meaning and function of the tags #biba and #boba in the bot's messages. Could you please provide more context or examples to clarify their usage?

Thank you for considering these suggestions!

**Comment by vorchunpaul** [comment]
man, biba and boba is literature character from classic russian history.
but im delete this to open my project to all world

and im not sure docs in this time is necessary.

**Comment by memExpert** [comment]
Thank you for the explanations. I understand now. I agree that documentation might not be the most critical part at this stage of the project’s development.
